### ISSUE TITLE
versatile.hpp ?

### ISSUE THREAD

**Issue by niXman** [tomilov/insituc#1]
Hi,

I found its inclusion in `https://github.com/tomilov/insituc/blob/master/include/insituc/variant.hpp#L4` file, but a cant googling it.

Ideas?

Thanks.

**Comment by tomilov** [comment]
@niXman It is [here](https://github.com/tomilov/variant/tree/master/include) but all this was so far ago.

**Comment by niXman** [comment]
Oh, thanks!

Closed.

**Comment by niXman** [comment]
May be better to refactor the `insituc` for using `std::variant`? Or its impossible?

**Comment by tomilov** [comment]
It really would be better. At that time there was no `std::variant`. I have no time for this project in the near perspective.

**Comment by niXman** [comment]
Ok, I understood.

Thank you.
